### ISSUE TITLE
redis: ranges generate ZSet spam into redis table

### ISSUE THREAD

**Issue by scbizu** [ezbuy/redis-orm#100]
## Issue Description

With the yaml definition like this:

```yaml
Blog:
  dbs: [redis]
  dbname: blog
  dbtable: user_blog
  fields:
    - ID: int64
      flags: [index]
    - Content: string
    - CreateDate: int64
    - UpdateDate: int64
primary: [ID]
```

In `object.go`, it will pass the `o.primary.IsRange()`, and create `o.ranges`:

```go 
if o.primary.IsRange() {
	index := NewIndex(o)
	index.FieldNames = o.primary.FieldNames
	o.ranges = append(o.ranges, index)
}
---
func (pk *PrimaryKey) IsRange() bool {
	c := len(pk.Fields)
	if c > 0 {
		return pk.Fields[c-1].IsNumber()
	}
	return false
}
```

And then, once we invoke our orm function `addToPipeline`, it will save the range info into redis table: 

```go 
	//! ranges
	rg_key_0 := []string{
		"Id",
	}
	rg_pip_0 := IdOfUserRNGRelationRedisMgr().BeginPipeline(pipe.Pipeline)
	rg_rel_0 := IdOfUserRNGRelationRedisMgr().NewIdOfUserRNGRelation(strings.Join(rg_key_0, ":"))
	score_rg_0, err := orm.ToFloat64(obj.Id)
	if err != nil {
		return err
	}
	rg_rel_0.Score = score_rg_0
	rg_rel_0.Value = key
	if err := rg_pip_0.ZSetAdd(rg_rel_0); err != nil {
		return err
	}
	if expire > 0 {
		pipe.Expire(keyOfObject(obj, key), expire)
	}
```
But, we do not need this kind of `range`, we only just need the `primary`  mechanism .

What 's more worse is that we store the `50%+` redis ranges(spam) into our redis , and they all have no TTL !!!

## Workarounds

How about add the `norange` flag into our redis column definition ?

Columns with `norange` flag will quit the range code generation, and then we can change our `primary.key.go` into this:

```go
func (pk *PrimaryKey) IsRange() bool {
      var fs []*Fields
      for _,f := range pk.Fields{
          if  !f.IsRange(){
            continue
         }
          fs = append(fs,f)
       }
   	c := len(fs)
	if c > 0 {
		return pk.Fields[c-1].IsNumber()
	}
  return false
}
```

**Comment by scbizu** [comment]
It will not generate IDRange anymore.

```yaml
Blog:
  dbs: [redis]
  dbname: blog
  dbtable: user_blog
  fields:
    - ID: int64
      flags: [index,norange]
    - Content: string
    - CreateDate: int64
    - UpdateDate: int64
primary: [ID]
```
