### ISSUE TITLE
parser: yaml field `sqlcolumn` not set db field

### ISSUE THREAD

**Issue by scbizu** [ezbuy/redis-orm#105]
## Reproduce

foo. yaml:
```yaml
Foo:
ID: int64
sqlcolumn: ID
```

gen.foo.go:
```
type Foo struct{
	ID  int64 `db:"id"`
}
```
