### ISSUE TITLE
proposal: pb plugin 

### ISSUE THREAD

**Issue by scbizu** [ezbuy/redis-orm#93]
## Background

At ezbuy, we use grpc protobuf as our protocol between all of ours ends. However, as for our backend(Go) team, we always have two main data structure, one is the DB scheme struct(generated by redis-orm), the other one is the pb scheme(generated by protoc), so , we always write some conversion wrappers , like:

```go
modelA := new(model.A)
// do sth to fill the modelA
pbA := &pb.A{
  AA: modelA.A,
  AB: modelA.B,
// etc...
}
```
Once the two struct becomes huge, our wasted time will also be boomed.

## Proposal

What about add the pb plugin into the redis-orm ?
```yaml
Blog:
  dbs: [mysql]
  dbname: ezorm
  dbtable: blogs
  fields:
    - Id: int32
    - UserId: int32
       pb: [UserID]
    - title: string
      es_do_index: true
      pb: [Title]
    - Content: string
      es_analyzer: standard
    - Status: int32
      flags: [index]
    - Readed: int32
    - CreatedAt: timestamp
      es_do_index: true
    - UpdatedAt: timestamp
  primary: [Id, UserId]
```   

And then, it will generate the extra pb conversion code like:

```go
package xxx

// ConvertModelToPB converts model to defined pb columns.
func ConvertModelToPB(md *model.Blog)*pb.Ezorm{
  return &pb.Ezorm{
     UserID: md.UserId,
     Title: md.Titel, 
 }
}

// ConvertPBToModel converts defined pb columns to model. 
func ConvertPBToModel(p *pb.Ezorm)*model.Blog{
 return &model.Blog{
   UserId: p.UserID,
   Title: p.Title,
 }
}
```

## Benefits 

* Decrease our wasted time on writing duplicated code.
* Decrease bugs caused by matching columns incorrectly.

## Risk 

* it will enlarge our generate codebase, and have no solutions to prevent abuse.

## Break compatibility ？

No.
